# WARNING: DON'T use the following validator key in production
apiVersion: v1
kind: Secret
metadata:
  name: validator-key
stringData:
  key: |-
    {
      "account_id": "validator",
      "public_key": "ed25519:CdTBLXMmu9gzoCbNKdUnej1tJNMz5tzRjJF2a9DwAgUr",
      "secret_key": "ed25519:4k83DwbSpD3zzai4ZPdeRJcfXttU3Uq68mWWhni6ra2RKnG3jyVKEZyP14gDJZ9W1oqFujpAkidoNrYY4TLqijsG"
    }
---
apiVersion: near.kotal.io/v1alpha1
kind: Node
metadata:
  name: near-validator-node
spec:
  network: mainnet
  validatorSecretName: validator-key
