---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-aptos-kotal-io-v1alpha1-node
  failurePolicy: Fail
  name: mutate-aptos-v1alpha1-node.kb.io
  rules:
  - apiGroups:
    - aptos.kotal.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - nodes
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-bitcoin-kotal-io-v1alpha1-node
  failurePolicy: Fail
  name: mutate-bitcoin-v1alpha1-node.kb.io
  rules:
  - apiGroups:
    - bitcoin.kotal.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - nodes
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-chainlink-kotal-io-v1alpha1-node
  failurePolicy: Fail
  name: mutate-chainlink-v1alpha1-node.kb.io
  rules:
  - apiGroups:
    - chainlink.kotal.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - nodes
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-ethereum-kotal-io-v1alpha1-node
  failurePolicy: Fail
  name: mutate-ethereum-v1alpha1-node.kb.io
  rules:
  - apiGroups:
    - ethereum.kotal.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - nodes
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-ethereum2-kotal-io-v1alpha1-beaconnode
  failurePolicy: Fail
  name: mutate-ethereum2-v1alpha1-beaconnode.kb.io
  rules:
  - apiGroups:
    - ethereum2.kotal.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - beaconnodes
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-ethereum2-kotal-io-v1alpha1-validator
  failurePolicy: Fail
  name: mutate-ethereum2-v1alpha1-validator.kb.io
  rules:
  - apiGroups:
    - ethereum2.kotal.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - validators
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-filecoin-kotal-io-v1alpha1-node
  failurePolicy: Fail
  name: mutate-filecoin-v1alpha1-node.kb.io
  rules:
  - apiGroups:
    - filecoin.kotal.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - nodes
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-ipfs-kotal-io-v1alpha1-clusterpeer
  failurePolicy: Fail
  name: mutate-ipfs-v1alpha1-clusterpeer.kb.io
  rules:
  - apiGroups:
    - ipfs.kotal.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - clusterpeers
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-ipfs-kotal-io-v1alpha1-peer
  failurePolicy: Fail
  name: mutate-ipfs-v1alpha1-peer.kb.io
  rules:
  - apiGroups:
    - ipfs.kotal.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - peers
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-near-kotal-io-v1alpha1-node
  failurePolicy: Fail
  name: mutate-near-v1alpha1-node.kb.io
  rules:
  - apiGroups:
    - near.kotal.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - nodes
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-polkadot-kotal-io-v1alpha1-node
  failurePolicy: Fail
  name: mutate-polkadot-v1alpha1-node.kb.io
  rules:
  - apiGroups:
    - polkadot.kotal.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - nodes
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-stacks-kotal-io-v1alpha1-node
  failurePolicy: Fail
  name: mutate-stacks-v1alpha1-node.kb.io
  rules:
  - apiGroups:
    - stacks.kotal.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - nodes
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-aptos-kotal-io-v1alpha1-node
  failurePolicy: Fail
  name: validate-aptos-v1alpha1-node.kb.io
  rules:
  - apiGroups:
    - aptos.kotal.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - nodes
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-bitcoin-kotal-io-v1alpha1-node
  failurePolicy: Fail
  name: validate-bitcoin-v1alpha1-node.kb.io
  rules:
  - apiGroups:
    - bitcoin.kotal.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - nodes
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-chainlink-kotal-io-v1alpha1-node
  failurePolicy: Fail
  name: validate-chainlink-v1alpha1-node.kb.io
  rules:
  - apiGroups:
    - chainlink.kotal.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - nodes
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-ethereum-kotal-io-v1alpha1-node
  failurePolicy: Fail
  name: validate-ethereum-v1alpha1-node.kb.io
  rules:
  - apiGroups:
    - ethereum.kotal.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - nodes
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-ethereum2-kotal-io-v1alpha1-beaconnode
  failurePolicy: Fail
  name: validate-ethereum2-v1alpha1-beaconnode.kb.io
  rules:
  - apiGroups:
    - ethereum2.kotal.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - beaconnodes
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-ethereum2-kotal-io-v1alpha1-validator
  failurePolicy: Fail
  name: validate-ethereum2-v1alpha1-validator.kb.io
  rules:
  - apiGroups:
    - ethereum2.kotal.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - validators
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-filecoin-kotal-io-v1alpha1-node
  failurePolicy: Fail
  name: validate-filecoin-v1alpha1-node.kb.io
  rules:
  - apiGroups:
    - filecoin.kotal.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - nodes
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-ipfs-kotal-io-v1alpha1-clusterpeer
  failurePolicy: Fail
  name: validate-ipfs-v1alpha1-clusterpeer.kb.io
  rules:
  - apiGroups:
    - ipfs.kotal.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - clusterpeers
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-ipfs-kotal-io-v1alpha1-peer
  failurePolicy: Fail
  name: validate-ipfs-v1alpha1-peer.kb.io
  rules:
  - apiGroups:
    - ipfs.kotal.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - peers
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-near-kotal-io-v1alpha1-node
  failurePolicy: Fail
  name: validate-near-v1alpha1-node.kb.io
  rules:
  - apiGroups:
    - near.kotal.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - nodes
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-polkadot-kotal-io-v1alpha1-node
  failurePolicy: Fail
  name: validate-polkadot-v1alpha1-node.kb.io
  rules:
  - apiGroups:
    - polkadot.kotal.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - nodes
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-stacks-kotal-io-v1alpha1-node
  failurePolicy: Fail
  name: validate-stacks-v1alpha1-node.kb.io
  rules:
  - apiGroups:
    - stacks.kotal.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - nodes
  sideEffects: None
