# permissions for end users to edit clusterpeers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterpeer-editor-role
rules:
  - apiGroups:
      - ipfs.kotal.io
    resources:
      - clusterpeers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ipfs.kotal.io
    resources:
      - clusterpeers/status
    verbs:
      - get
