# WARNING: DON'T use the following secrets in production
apiVersion: v1
kind: Secret
metadata:
  name: ibft2-besu-nodekey
stringData:
  key: 608e9b6f67c65e47531e08e8e501386dfae63a540fa3c48802c8aad854510b4e
---
apiVersion: ethereum.kotal.io/v1alpha1
kind: Node
metadata:
  name: ibft2-besu-node
spec:
  ########### Genesis block spec ###########
  genesis:
    chainId: 20189
    networkId: 11
    ibft2:
      blockPeriod: 2
      epochLength: 30000
      requestTimeout: 10
      validators:
        - "0x427e2c7cecd72bc4cdd4f7ebb8bb6e49789c8044"
        - "0xd2c21213027cbf4d46c16b55fa98e5252b048706"
        - "0x8e1f6c7c76a1d7f74eda342d330ca9749f31cc2b"
    forks:
      homestead: 0
      eip150: 0
      eip155: 0
      eip158: 0
      byzantium: 0
      constantinople: 0
      petersburg: 0
      istanbul: 0
      muirglacier: 0
      berlin: 0
      london: 0
      arrowGlacier: 0
    coinbase: "0x071E2c1067c24607fF00cEEBbe83a38063BDEDd8"
    difficulty: "0xfff"
    gasLimit: "0x47b760"
    nonce: "0x0"
    timestamp: "0x0"
    accounts:
      - address: "0x48c5F25a884116d58A6287B72C9b069F936C9489"
        balance: "0xffffffffffffffffffff"
  ########### node spec ###########
  client: besu
  rpc: true
  nodePrivateKeySecretName: ibft2-besu-nodekey
  rpcPort: 8599
  corsDomains:
    - all
  hosts:
    - all
  rpcAPI:
    - web3
    - net
    - eth
    - ibft
  resources:
    cpu: "1"
    cpuLimit: "1"
    memory: "1Gi"
    memoryLimit: "2Gi"
