# WARNING: DON'T use the following secrets in production
apiVersion: v1
kind: Secret
metadata:
  name: poa-besu-nodekey
stringData:
  key: 608e9b6f67c65e47531e08e8e501386dfae63a540fa3c48802c8aad854510b4e
---
apiVersion: ethereum.kotal.io/v1alpha1
kind: Node
metadata:
  name: poa-besu-node
spec:
  ########### Genesis block spec ###########
  genesis:
    chainId: 20189
    networkId: 11
    clique:
      signers:
        - "0xd2c21213027cbf4d46c16b55fa98e5252b048706"
    accounts:
      - address: "0x48c5F25a884116d58A6287B72C9b069F936C9489"
        balance: "0xffffffffffffffffffff"
  ########### node spec ###########
  client: besu
  rpc: true
  nodePrivateKeySecretName: poa-besu-nodekey
  rpcPort: 8599
  corsDomains:
    - all
  hosts:
    - all
  rpcAPI:
    - web3
    - net
    - eth
    - clique
  resources:
    cpu: "1"
    cpuLimit: "1"
    memory: "1Gi"
    memoryLimit: "2Gi"
