# WARNING: DON'T use the following secrets in production
apiVersion: v1
kind: Secret
metadata:
  name: pow-geth-account-key
stringData:
  # address 0x2b3430337f12Ce89EaBC7b0d865F4253c7744c0d
  key: 5df5eff7ef9e4e82739b68a34c6b23608d79ee8daf3b598a01ffb0dd7aa3a2fd
---
apiVersion: v1
kind: Secret
metadata:
  name: pow-geth-account-password
stringData:
  password: secret
---
apiVersion: ethereum.kotal.io/v1alpha1
kind: Node
metadata:
  name: pow-geth-node
spec:
  ########### Genesis block spec ###########
  genesis:
    chainId: 9999
    networkId: 11
    ethash: {}
    accounts:
      - address: "0x48c5F25a884116d58A6287B72C9b069F936C9489"
        balance: "0xffffffffffffffffffff"
  ########### node spec ###########
  client: geth
  miner: true
  coinbase: "0x2b3430337f12Ce89EaBC7b0d865F4253c7744c0d"
  import:
    privateKeySecretName: pow-geth-account-key
    passwordSecretName: pow-geth-account-password
  resources:
    cpu: "1"
    cpuLimit: "1"
    memory: "1Gi"
    memoryLimit: "2Gi"
