# WARNING: DON'T use the following secrets in production
apiVersion: v1
kind: Secret
metadata:
  name: mainnet-besu-nodekey
stringData:
  key: 5df5eff7ef9e4e82739b68a34c6b23608d79ee8daf3b598a01ffb0dd7aa3a2fd
---
apiVersion: ethereum.kotal.io/v1alpha1
kind: Node
metadata:
  name: mainnet-besu-node
spec:
  network: mainnet
  client: besu
  nodePrivateKeySecretName: mainnet-besu-nodekey
  rpc: true
  rpcPort: 8599
  corsDomains:
    - example.kotal.io
  rpcAPI:
    - web3
    - net
    - eth
  graphql: true
  graphqlPort: 8777
  resources:
    cpu: "1"
    cpuLimit: "1"
    memory: "1Gi"
    memoryLimit: "2Gi"
