# WARNING: DON'T use the following secrets in production
apiVersion: v1
kind: Secret
metadata:
  name: pow-besu-nodekey
stringData:
  # address 0x5A0b54D5dc17e0AadC383d2db43B0a0D3E029c4c
  key: 608e9b6f67c65e47531e08e8e501386dfae63a540fa3c48802c8aad854510b4e
---
apiVersion: ethereum.kotal.io/v1alpha1
kind: Node
metadata:
  name: pow-besu-node
spec:
  ########### Genesis block spec ###########
  genesis:
    chainId: 9999
    networkId: 11
    ethash: {}
    accounts:
      - address: "0x48c5F25a884116d58A6287B72C9b069F936C9489"
        balance: "0xffffffffffffffffffff"
  ########### node spec ###########
  client: besu
  miner: true
  coinbase: "0x5A0b54D5dc17e0AadC383d2db43B0a0D3E029c4c"
  nodePrivateKeySecretName: pow-besu-nodekey
  rpc: true
  rpcPort: 8599
  corsDomains:
    - all
  hosts:
    - all
  rpcAPI:
    - web3
    - net
    - eth
  resources:
    cpu: "1"
    cpuLimit: "1"
    memory: "1Gi"
    memoryLimit: "2Gi"
