# WARNING: DON'T use the following secrets in production
apiVersion: v1
kind: Secret
metadata:
  name: poa-nethermind-account-key
stringData:
  # address 0x1990E5760d9f8Ae0ec55dF8B0819C77e59846Ff2
  key: bb30a68be4d1f8b54755398f81704fcbd00df4aa7d3cad02547d61291ac252b0
---
apiVersion: v1
kind: Secret
metadata:
  name: poa-nethermind-account-password
stringData:
  password: secret
---
apiVersion: ethereum.kotal.io/v1alpha1
kind: Node
metadata:
  name: poa-nethermind-node
spec:
  ########### Genesis block spec ###########
  genesis:
    chainId: 20189
    networkId: 20189
    clique:
      blockPeriod: 15
      epochLength: 100
      signers:
        - "0xcF2C3fB8F36A863FD1A8c72E2473f81744B4CA6C"
        - "0x1990E5760d9f8Ae0ec55dF8B0819C77e59846Ff2"
        - "0xB87c1c66b36D98D1A74a9875EbA12c001e0bcEda"
    forks:
      homestead: 0
      eip150: 0
      eip155: 0
      eip158: 0
      byzantium: 0
      constantinople: 0
      petersburg: 0
      istanbul: 0
      muirglacier: 0
      berlin: 0
      london: 0
      arrowGlacier: 0
    coinbase: "0x071E2c1067c24607fF00cEEBbe83a38063BDEDd8"
    difficulty: "0xfff"
    gasLimit: "0x47b760"
    nonce: "0x0"
    timestamp: "0x0"
    accounts:
      - address: "0x48c5F25a884116d58A6287B72C9b069F936C9489"
        balance: "0xffffffffffffffffffff"
  ########### node spec ###########
  client: nethermind
  logging: info
  miner: true
  coinbase: "0x1990E5760d9f8Ae0ec55dF8B0819C77e59846Ff2"
  import:
    privateKeySecretName: poa-nethermind-account-key
    passwordSecretName: poa-nethermind-account-password
  syncMode: full
  staticNodes:
    - "enode://36f50b80f06135c8d2871d1c0c2faee6d3d952f8c100870fc41d61ac9e535fa6367409f9b2ac8658147273677f90c9fddee4f9269dad069a1f78ae3297a13b2e@10.96.161.221:30303"
  resources:
    cpu: "1"
    memory: "1Gi"
