# WARNING: DON'T use the following secrets in production
apiVersion: v1
kind: Secret
metadata:
  name: pow-besu-nodekey
stringData:
  # address 0x5A0b54D5dc17e0AadC383d2db43B0a0D3E029c4c
  key: 608e9b6f67c65e47531e08e8e501386dfae63a540fa3c48802c8aad854510b4e
---
apiVersion: ethereum.kotal.io/v1alpha1
kind: Node
metadata:
  name: pow-besu-node
spec:
  ########### Genesis block spec ###########
  genesis:
    chainId: 20189
    networkId: 20189
    ethash: {}
    forks:
      homestead: 0
      eip150: 0
      eip155: 0
      eip158: 0
      byzantium: 0
      constantinople: 0
      petersburg: 0
      istanbul: 0
      muirglacier: 0
      berlin: 0
      london: 0
      arrowGlacier: 0
    coinbase: "0x071e2c1067c24607ff00ceebbe83a38063bdedd8"
    difficulty: "0x1"
    gasLimit: "0x47b760"
    nonce: "0x0"
    timestamp: "0x5f69fcd9"
    accounts:
      - address: "0x48c5F25a884116d58A6287B72C9b069F936C9489"
        balance: "0xffffffffffffffffffff"
  ########### node spec ###########
  client: besu
  miner: true
  nodePrivateKeySecretName: pow-besu-nodekey
  coinbase: "0x5A0b54D5dc17e0AadC383d2db43B0a0D3E029c4c"
  rpc: true
  rpcPort: 8599
  corsDomains:
    - all
  hosts:
    - all
  rpcAPI:
    - web3
    - net
    - eth
  resources:
    cpu: "1"
    cpuLimit: "1"
    memory: "1Gi"
    memoryLimit: "2Gi"
